id: P001759
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG1592
  title: ས་སྐྱ་ལེགས་བཤད་དོན་འགྲེལ
  author: ''
  volumes:
    f60736daf0e94d668794d1f99491b1ab:
      image_group_id: I1KG1871
      title: ''
      volume_number: 1
      total_pages: 416
      base_file: v001.txt
